services:
  backend:
    build: ./backend
    container_name: ftth_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ftth
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: ftth_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ./frontend/ftth-dashboard
    container_name: ftth_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
